### ISSUE TITLE
Plugin with id 'com.jakewharton.hugo' not found

### ISSUE THREAD

**Issue by mysizeofcn** [mobvoi/ticdesign#4]
Error:(18, 0) Plugin with id 'com.jakewharton.hugo' not found.
<a href="openFile:/Users/Web/Downloads/Reader/demo/build.gradle">Open File</a>

请问这个问题怎么解决呀？

**Comment by tankery** [comment]
这是个方便调试的插件。需要在root project 的 `build.gradle` 里面添加一些依赖。
详情可以看根目录的 `build.gradle` 或者参考[原作者的文档](https://github.com/JakeWharton/hugo)
