### ISSUE TITLE
与com.google.android.wearable:wearable:2.1.0冲突

### ISSUE THREAD

**Issue by CavellChance** [mobvoi/ticdesign#8]
Error:(59, 1) error: resource android:attr/buttonPanelSideLayout is private.
Error:(59, 1) error: resource android:attr/progressLayout is private.
Error:(59, 1) error: resource android:attr/horizontalProgressLayout is private.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':wear:processDebugResources'.
> Failed to execute aapt
与wearable:2.1.0的属性名冲突了，还是wearable:2.1.0的权限改了？

**Comment by tankery** [comment]
@CavellChance 是以前正常，升级 wearable:2.1.0  时出错还是第一次使用？
能否把 build.gradle 文件的相关部分贴出来看看。

请注意 google 的 wearable 库只能通过 provided （gradle 3.0 是 compileOnly）方式依赖。

**Comment by CavellChance** [comment]
![image](https://user-images.githubusercontent.com/8696346/33749660-f001dbb8-dc09-11e7-970a-c2d09b0c6dcf.png)

**Comment by tankery** [comment]
@CavellChance 你再检查一下看看是否是其他库的冲突（比如是不是 wear-tools 的冲突）？我们项目中也是使用了`com.google.android.wearable:wearable` 和 `com.google.android.support:wearable`，我尝试了升级到 2.1.0，并没有出现冲突。

**Comment by tankery** [comment]
@CavellChance 最近我们复现了这个问题。发现与 wearable 库的版本无关，而是与升级 gradle 3.0 有关。

目前已经做了修复，发布了新版本，你可以更新到 TicDesign 1.1.0 版本来解决此问题。

**Comment by ichenhe** [comment]
升级到 gradle 5.6.4, gradle 插件 3.6.1 后复现。
