### ISSUE TITLE
Unknown android attribute 'AlertDialog'

### ISSUE THREAD

**Issue by zlrambo** [mobvoi/ticdesign#9]
demo代码放在Android Studio编译通不过，报此错误：Execution failed for task ':ticdesign:processDebugResources'.
> Unknown android attribute 'AlertDialog'

**Comment by tankery** [comment]
@zlrambo 你是用 gradlew 编译的吗？能否提供下更多的错误信息？我们测试都可以编译成功。

**Comment by zlrambo** [comment]
谢谢回答，此错误已经解决，还有个问题想咨询一下，TicWear 2 launcher中在表盘界面上下左右都可以滑出界面这是用的什么框架，能开源出来吗？

**Comment by tankery** [comment]
@zlrambo 这个项目没有开源。launcher 是一个 App，上下左右的滑动都是 App 内的交互。

**Comment by zlrambo** [comment]
好的，谢谢，这种交互我目前还没想到好的解决方案，能提供一下思路吗？

**Comment by tankery** [comment]
@zlrambo 并没什么特别的思路。就是普通的 App 内的页面交互而已。

**Comment by shaoyie** [comment]
@zlrambo 你好，我们现在也遇到
Execution failed for task ':ticdesign:processDebugResources'.
Unknown android attribute 'AlertDialog'
同样的问题，想请问一下你当时是怎么解决的？
